

resources_between_areas = {1: {'Feral Shard': 12,
  'Condensed Volatility': 1,
  'Chittering Shard': 11,
  'Bold Straps': 1,
  'Cockatrice Soul': 3,
  'Feral Ember': 3,
  'Chittering Ember': 3,
  'Beetle Soul': 1,
  'Sorrowful Shard': 15,
  'Sorrowful Ember': 3,
  'Disturbing Shard': 7,
  ' Sorrowful Ember': 2,
  'Vampyre Soul': 1,
  'Vampyre Soul1Feral Shard': 4,
  'Reckless Abandon': 2,
  'Disturbing Ember': 3,
  'Parasitic Soul': 1,
  'Soaring Ember': 4,
  'Harpy Sould': 2,
  'Cunning Ember': 5,
  'Canon Soul': 1},
 2: {'Bold Straps': 1,
  'Feral Shard': 15,
  'Feral Ember': 2,
  'Comfy Robe': 1,
  'Chittering Shard': 15,
  'Cockatrice Soul': 2,
  'Chittering Ember': 3,
  'Beetle Soul': 1,
  'Sorrowful Shard': 18,
  'Disturbing Shard': 11,
  'Sorrowful Ember': 3,
  ' Vampyre Soul': 1,
  'Disturbing Ember': 8,
  'Cunning Ember': 9,
  'Parasitic Soul': 1,
  'Soaring Ember': 6,
  'Harpy Sould': 2,
  'Canon Soul': 1},
 3: {'Feral Shard': 25,
  'Chittering Shard': 21,
  'Cockatrice Soul': 2,
  'Feral Ember': 5,
  'Chittering Ember': 4,
  'Condensed Volatility': 1,
  'Beetle Soul': 4,
  'Sorrowful Shard': 14,
  'Sorrowful Ember': 7,
  'Sorrowful Ember3Vampyre Soul': 2,
  'Feral Shard4Feral Ember': 2,
  'Disturbing Shard': 11,
  'Disturbing Ember': 8,
  'Cunning Ember': 11,
  'Cunning Ember2Crosshair Bandana': 1,
  'Parasitic Soul': 1,
  'Soaring Ember': 4,
  'Harpy Sould': 2,
  'Corsair Bandana': 1,
  'Canon Soul': 1},
 4: {'Feral Shard': 16,
  'Cockatrice Soul': 2,
  'Feral Ember': 2,
  'Chittering Shard': 16,
  'Condensed Volatility': 1,
  'Circlet of Bold': 1,
  'Chittering Ember': 2,
  'Beetle Soul': 1,
  'Deeper Than Sound': 1,
  'Sorrowful Shard': 7,
  'Disturbing Shard': 5,
  'Sorrowful Ember': 3,
  'Sorrowful Ember3 Vampyre Soul': 2,
  'Disturbing Ember': 8,
  'Parasitic Soul': 2,
  'Night Seeker': 1,
  "Witch's Robe": 1,
  'Soaring Ember': 6,
  'Harpy Sould': 1,
  'Cunning Ember': 7,
  'Canon Soul': 1},
 5: {'Feral Shard': 7,
  'Feral Ember': 4,
  'Bold Straps': 1,
  'Cockatrice Soul': 2,
  'Chittering Shard': 13,
  'Circlet of Bold': 1,
  'Piligrims Staff': 1,
  'Chittering Ember': 4,
  'Beetle Soul': 4,
  'Sorrowful Ember': 4,
  'Sorrowful Shard': 6,
  'Natures Gift': 1,
  'Vampyre Soul': 3,
  'Disturbing Ember': 3,
  "Witchs's robe": 1,
  'Disturbing Shard': 6,
  'Joy Bringer': 1,
  'Parasitic Soul': 2,
  'Soaring Ember': 5,
  'Cunning Ember': 6,
  'Harpy Sould': 2,
  'Canon Soul': 1},
 6: {'Feral Shard': 28,
  'Cockatrice Soul': 2,
  'Feral Ember': 6,
  'Chittering Shard': 20,
  ' Chittering Ember': 4,
  ' Beetle Soul': 2,
  'Sorrowful Shard': 12,
  'Sorrowful Ember': 4,
  'Disturbing Shard': 13,
  'Vampyre Soul': 1,
  'Disturbing Ember': 7,
  'Cunning Ember': 11,
  'Parasitic Soul': 1,
  'Soaring Ember': 5,
  'Harpy Sould': 1,
  'Canon Soul': 1},
 7: {'Feral Shard': 14,
  'Chittering Shard': 17,
  'Feral Ember': 4,
  'Bold Straps': 1,
  'Cockatrice Soul': 2,
  ' Chittering Ember': 4,
  ' Beetle Soul': 4,
  'Sorrowful Shard': 10,
  ' Sorrowful Ember': 1,
  'Sorrowful Ember': 1,
  'Vampyre Soul': 1,
  'Vampyre Soul1Feral Shard': 3,
  'Disturbing Ember': 4,
  'Disturbing Shard': 8,
  'Cunning Ember': 8,
  'Parasitic Soul': 2,
  'Soaring Ember': 6,
  'Harpy Sould': 2,
  'Night Walker': 2,
  'Tactician Helm': 1,
  'Corsair Bandana': 1,
  'Canon Soul': 1},
 8: {'Condensed Volatility': 2,
  'Feral Shard': 22,
  'Chittering Shard': 10,
  'Feral Ember': 7,
  'Bold Straps': 1,
  'Cockatrice Soul': 4,
  ' Chittering Ember': 3,
  'Beetle Soul': 2,
  'Sorrowful Shard': 11,
  'Sorrowful Ember': 4,
  'Disturbing Shard': 13,
  'Vampyre Soul': 2,
  'Disturbing Ember': 5,
  'Parasitic Soul': 2,
  'Soaring Ember': 2,
  'Cunning Ember': 5,
  'Harpy Sould': 1,
  'Canon Soul': 1},
 9: {'Feral Shard': 12,
  'Chittering Shard': 18,
  'Feral Ember': 3,
  'Cockatrice Soul': 1,
  ' Chittering Ember': 1,
  'Beetle Soul': 1,
  'Sorrowful Shard': 13,
  'Sorrowful Ember': 4,
  'Vampyre Soul': 1,
  'Sorrowful Ember2Vampyre Soul': 1,
  'Feral Shard3Devouring Scythe': 1,
  'Disturbing Ember': 5,
  "Witchs's robe": 1,
  'Disturbing Shard': 9,
  'Parasitic Soul': 1,
  'Soaring Ember': 3,
  'Harpy Sould': 1,
  'Cunning Ember': 4,
  'Canon Soul': 1},
 10: {'Cunning Ember': 14,
  'Canon Soul': 2,
  'Feral Ember': 3,
  'Feral Shard': 10,
  'Chittering Shard': 13,
  'Bold Straps': 1,
  'Cockatrice Soul': 2,
  ' Chittering Ember': 1,
  'Beetle Soul': 2,
  'Sorrowful Shard': 13,
  'Sorrowful Ember': 1,
  ' Sorrowful Ember': 3,
  ' Sorrowful Ember3 Vampyre Soul': 2,
  'Disturbing Ember': 11,
  'Disturbing Shard': 18,
  'Parasitic Soul': 1,
  'Soaring Ember': 4,
  'Harpy Sould': 2}}