

resources_between_areas = {1: {'Feral Shard': 6,
 'Condensed Volatility': 1,
 'Chittering Shard': 11,
 'Bold Straps': 1,
 'Cockatrice Soul': 1,
 'Feral Ember': 1,
 'Chittering Ember': 3,
 'Beetle Soul': 1,
 'Sorrowful Shard': 15,
 'Sorrowful Ember': 5,
 'Disturbing Shard': 7,
 'Vampyre Soul': 2,
 'Reckless Abandon': 2,
 'Disturbing Ember': 3,
 'Parasitic Soul': 1,
 'Soaring Ember': 4,
 'Harpy Sould': 2,
 'Cunning Ember': 5,
 'Canon Soul': 1},
 2: {'Cockatrice Soul': 3,
 'Bold Straps': 2,
 'Sorrowful Shard': 33,
 'Soaring Ember': 10,
 'Reckless Abandon': 2,
 'Canon Soul': 2,
 'Harpy Sould': 4,
 'Chittering Ember': 6,
 'Feral Ember': 3,
 'Disturbing Ember': 11,
 'Beetle Soul': 2,
 'Comfy Robe': 1,
 'Feral Shard': 21,
 'Condensed Volatility': 1,
 'Vampyre Soul': 3,
 'Cunning Ember': 14,
 'Sorrowful Ember': 8,
 'Parasitic Soul': 2,
 'Chittering Shard': 26,
 'Disturbing Shard': 18},
 3: {'Cockatrice Soul': 5,
 'Bold Straps': 2,
 'Sorrowful Shard': 44,
 'Soaring Ember': 14,
 'Reckless Abandon': 2,
 'Canon Soul': 3,
 'Corsair Bandana': 1,
 'Harpy Sould': 6,
 'Chittering Ember': 9,
 'Feral Ember': 7,
 'Disturbing Ember': 19,
 'Beetle Soul': 4,
 'Comfy Robe': 1,
 'Feral Shard': 43,
 'Condensed Volatility': 2,
 'Vampyre Soul': 3,
 'Cunning Ember': 27,
 'Sorrowful Ember': 15,
 'Parasitic Soul': 3,
 'Chittering Shard': 40,
 'Disturbing Shard': 29},
 4: {'Sorrowful Shard': 49,
 'Soaring Ember': 20,
 'Corsair Bandana': 1,
 'Harpy Sould': 7,
 'Chittering Ember': 11,
 'Beetle Soul': 5,
 'Circlet of Bold': 1,
 'Condensed Volatility': 3,
 'Cunning Ember': 34,
 'Disturbing Shard': 34,
 'Night Seeker': 1,
 'Cockatrice Soul': 7,
 'Bold Straps': 2,
 'Reckless Abandon': 2,
 'Canon Soul': 4,
 "Witch's Robe": 1,
 'Deeper Than Sound': 1,
 'Feral Ember': 9,
 'Disturbing Ember': 26,
 'Comfy Robe': 1,
 'Feral Shard': 55,
 'Vampyre Soul': 3,
 'Sorrowful Ember': 21,
 'Parasitic Soul': 5,
 'Chittering Shard': 56},
 5: {'Sorrowful Shard': 55,
 'Soaring Ember': 25,
 'Corsair Bandana': 1,
 'Harpy Sould': 9,
 'Joy Bringer': 1,
 'Chittering Ember': 13,
 'Piligrims Staff': 1,
 'Beetle Soul': 7,
 'Circlet of Bold': 2,
 'Condensed Volatility': 3,
 "Witchs's Robe": 1,
 'Cunning Ember': 40,
 'Disturbing Shard': 40,
 'Night Seeker': 1,
 'Cockatrice Soul': 9,
 'Bold Straps': 3,
 'Reckless Abandon': 2,
 'Natures Gift': 1,
 'Canon Soul': 5,
 "Witch's Robe": 1,
 'Deeper Than Sound': 1,
 'Feral Ember': 13,
 'Disturbing Ember': 29,
 'Comfy Robe': 1,
 'Feral Shard': 62,
 'Vampyre Soul': 6,
 'Sorrowful Ember': 25,
 'Parasitic Soul': 7,
 'Chittering Shard': 66},
 6: {'Sorrowful Shard': 67,
 'Soaring Ember': 30,
 'Corsair Bandana': 1,
 'Harpy Sould': 10,
 'Joy Bringer': 1,
 'Chittering Ember': 15,
 'Piligrims Staff': 1,
 'Beetle Soul': 8,
 'Circlet of Bold ': 2,
 'Condensed Volatility': 3,
 "Witchs's Robe": 1,
 'Cunning Ember': 51,
 'Disturbing Shard': 53,
 'Night Seeker': 1,
 'Cockatrice Soul': 10,
 'Bold Straps': 3,
 'Reckless Abandon': 2,
 'Natures Gift': 1,
 'Canon Soul': 6,
 "Witch's Robe": 1,
 'Deeper Than Sound': 1,
 'Feral Ember': 16,
 'Disturbing Ember': 36,
 'Comfy Robe': 1,
 'Feral Shard': 80,
 'Vampyre Soul': 7,
 'Sorrowful Ember': 29,
 'Parasitic Soul': 8,
 'Chittering Shard': 80},
 7: {'Sorrowful Shard': 77,
 'Soaring Ember': 36,
 'Corsair Bandana': 2,
 'Harpy Sould': 12,
 'JoyBringer': 1,
 'Chittering Ember': 17,
 'Piligrims Staff': 1,
 'Beetle Soul': 10,
 'Circlet of Bold ': 2,
 'Condensed Volatility': 3,
 "Witchs's Robe": 1,
 'Cunning Ember': 59,
 'Disturbing Shard': 61,
 'Night Seeker': 1,
 'Cockatrice Soul': 12,
 'Night Walker': 2,
 'Bold Straps': 4,
 'Reckless Abandon': 2,
 'Natures Gift': 1,
 'Canon Soul': 7,
 "Witch's Robe": 1,
 'Deeper Than Sound': 1,
 'Feral Ember': 20,
 'Disturbing Ember': 40,
 'Comfy Robe': 1,
 'Feral Shard': 94,
 'Vampyre Soul': 9,
 'Sorrowful Ember': 31,
 'Parasitic Soul': 10,
 'Tactician Helm': 1,
 'Chittering Shard': 93},
 8: {'Sorrowful Shard': 88,
 'Soaring Ember': 38,
 'Corsair Bandana': 2,
 'Harpy Sould': 13,
 'Joy Bringer': 1,
 'Chittering Ember': 20,
 'Piligrims Staff': 1,
 'Beetle Soul': 12,
 'Circlet of Bold ': 2,
 'Condensed Volatility': 5,
 "Witchs's Robe": 1,
 'Cunning Ember': 64,
 'Disturbing Shard': 74,
 'Night Seeker': 1,
 'Cockatrice Soul': 14,
 'Night Walker': 2,
 'Bold Straps': 5,
 'Reckless Abandon': 2,
 'Natures Gift': 1,
 'Canon Soul': 8,
 "Witch's Robe": 1,
 'Deeper Than Sound': 1,
 'Feral Ember': 24,
 'Disturbing Ember': 45,
 'Comfy Robe': 1,
 'Feral Shard': 111,
 'Vampyre Soul': 11,
 'Sorrowful Ember': 35,
 'Parasitic Soul': 12,
 'Tactician Helm': 1,
 'Chittering Shard': 103},
 9: {'Sorrowful Shard': 101,
 'Soaring Ember': 41,
 'Corsair Bandana': 2,
 'Harpy Sould': 14,
 'Joy Bringer': 1,
 'Chittering Ember': 21,
 'Piligrims Staff': 1,
 'Beetle Soul': 13,
 'Circlet of Bold ': 2,
 'Condensed Volatility': 5,
 "Witchs's Robe": 2,
 'Cunning Ember': 68,
 'Disturbing Shard': 83,
 'Night Seeker': 1,
 'Cockatrice Soul': 15,
 'Night Walker': 2,
 'Bold Straps': 5,
 'Reckless Abandon': 2,
 'Natures Gift': 1,
 'Canon Soul': 9,
 "Witch's Robe": 1,
 'Deeper Than Sound': 1,
 'Feral Ember': 27,
 'Disturbing Ember': 50,
 'Comfy Robe': 1,
 'Feral Shard': 126,
 'Vampyre Soul': 12,
 'Sorrowful Ember': 41,
 'Parasitic Soul': 13,
 'Tactician Helm': 1,
 'Chittering Shard': 117},
 10: {'Sorrowful Shard': 114,
 'Soaring Ember': 45,
 'Corsair Bandana': 2,
 'Harpy Sould': 16,
 'Joy Bringer': 1,
 'Chittering Ember': 22,
 'Piligrims Staff': 1,
 'Beetle Soul': 15,
 'Circlet of Bold ': 2,
 'Condensed Volatility': 5,
 "Witchs's Robe": 2,
 'Cunning Ember': 78,
 'Disturbing Shard': 95,
 'Night Seeker': 1,
 'Cockatrice Soul': 17,
 'Night Walker': 2,
 'Bold Straps': 6,
 'Reckless Abandon': 2,
 'Natures Gift': 1,
 'Canon Soul': 10,
 "Witch's Robe": 1,
 'Deeper Than Sound': 1,
 'Feral Ember': 30,
 'Disturbing Ember': 59,
 'Comfy Robe': 1,
 'Feral Shard': 136,
 'Vampyre Soul': 12,
 'Sorrowful Ember': 48,
 'Parasitic Soul': 14,
 'Tactician Helm': 1,
 'Chittering Shard': 130}}