

resources_between_areas = {1: {'Feral Shard': 12,
  'Condensed Volatility': 1,
  'Bold Straps': 1,
  'Chittering Shard': 10,
  'Sorrowful Shard': 15,
  'Reckless Abandon': 2,
  'Disturbing Ember': 1,
  'Parasitic Soul': 1,
  'Soaring Ember': 4,
  'Cunning Ember': 5},
 2: {'Bold Straps': 1,
  'Feral Ember': 1,
  'Chittering Shard': 15,
  'Feral Shard': 5,
  'Sorrowful Shard': 18,
  'Disturbing Shard': 5,
  'Parasitic Soul': 1,
  'Soaring Ember': 6,
  'Cunning Ember': 5},
 3: {'Feral Shard': 11,
  'Chittering Shard': 21,
  'Sorrowful Shard': 14,
  'Sorrowful Ember': 1,
  'Disturbing Shard': 7,
  'Parasitic Soul': 1,
  'Soaring Ember': 4,
  'Cunning Ember': 7},
 4: {'Feral Shard': 16,
  'Chittering Shard': 16,
  'Sorrowful Shard': 7,
  'Disturbing Shard': 2,
  'Disturbing Ember': 3,
  'Parasitic Soul': 2,
  'Soaring Ember': 6,
  'Cunning Ember': 7},
 5: {'Feral Shard': 7,
  'Feral Ember': 1,
  'Bold Straps': 1,
  'Chittering Shard': 13,
  'Circlet of Bold': 1,
  'Sorrowful Ember': 2,
  'Sorrowful Shard': 6,
  'Disturbing Ember': 1,
  'Disturbing Shard': 3,
  'Parasitic Soul': 2,
  'Soaring Ember': 5,
  'Cunning Ember': 5},
 6: {'Feral Shard': 24,
  'Chittering Shard': 20,
  'Sorrowful Shard': 12,
  'Disturbing Ember': 3,
  'Disturbing Shard': 6,
  'Parasitic Soul': 1,
  'Soaring Ember': 5,
  'Cunning Ember': 7},
 7: {'Feral Shard': 11,
  'Chittering Shard': 17,
  'Bold Straps': 1,
  'Sorrowful Shard': 10,
  'Disturbing Ember': 2,
  'Disturbing Shard': 5,
  'Parasitic Soul': 2,
  'Soaring Ember': 6,
  'Cunning Ember': 4},
 8: {'Condensed Volatility': 2,
  'Chittering Shard': 10,
  'Bold Straps': 1,
  'Feral Shard': 10,
  'Sorrowful Shard': 11,
  'Disturbing Ember': 2,
  'Disturbing Shard': 7,
  'Parasitic Soul': 2,
  'Soaring Ember': 2,
  'Cunning Ember': 5},
 9: {'Feral Shard': 9,
  'Chittering Shard': 18,
  'Sorrowful Shard': 13,
  'Disturbing Ember': 2,
  'Disturbing Shard': 5,
  'Parasitic Soul': 1,
  'Soaring Ember': 3,
  'Cunning Ember': 4},
 10: {'Cunning Ember': 8,
  'Feral Ember': 1,
  'Chittering Shard': 13,
  'Feral Shard': 5,
  'Sorrowful Shard': 13,
  'Disturbing Ember': 2,
  'Disturbing Shard': 12,
  'Parasitic Soul': 1,
  'Soaring Ember': 4}}